name = "proxy-indonesia"
compatibility_date = "2025-01-15"
main = "worker.js"

[vars]
PROXY_LIST_URL = "https://raw.githubusercontent.com/adipatijowo/indonesiq-proxy/refs/heads/main/proxy-list.json"
SUB_PAGE_URL = ""

# ===== ADD THIS =====
[[kv_namespaces]]
binding = "indo"
id = "3dfe761d25f844d28a460d63c2ee57f1"
