name = "https://indo.kayatinur505.workers.dev/"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "565a8c9db20f59000191b483cadf196d"
workers_dev = true

[vars]
# Gunakan Wrangler Secrets untuk kredensial yang lebih aman
#USERNAME = "username-yang-aman"
#PASSWORD = "password-yang-aman"
PROXY_LIST_URL = "https://raw.githubusercontent.com/adipatijowo/indonesiq-proxy/refs/heads/main/proxy-list.json"

[kv_namespaces]
bindings = [
  { name = "indo", id = "3dfe761d25f844d28a460d63c2ee57f1" }
]
