name = "https://indo.kayatinur505.workers.dev/"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "id-akun-cloudflare-kamu"
workers_dev = true

[vars]
# Gunakan Wrangler Secrets untuk kredensial yang lebih aman
#USERNAME = "username-yang-aman"
#PASSWORD = "password-yang-aman"
PROXY_LIST_URL = "https://url-raw-json-proxy-kamu.com/proxy-list.json"

[kv_namespaces]
bindings = [
  { name = "SESSION_KV", id = "id-namespace-kv-kamu" }
]
